### ISSUE TITLE
ERROR - No bean named 'baseContentTransformer' available

### ISSUE THREAD

**Issue by renatofritola** [Alfresco/alfresco-community-repo#414]
When trying to start Alfresco in version 7.0, the following error occurs:

`
2021-04-26 11:39:06,707  ERROR [web.context.ContextLoader] [main] Context initialization failed

org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'patch.updateAdminUserWhenDefault' defined in URL [jar:file:/usr/local/tomcat/webapps/alfresco/WEB-INF/lib/alfresco-repository-8.423.jar!/alfresco/patch/patch-services-context.xml]: Invocation of init method failed; nested exception is org.springframework.beans.factory.BeanDefinitionStoreException: Invalid bean definition with name 'transformer.onlyoffice' defined in URL [jar:file:/usr/local/tomcat/webapps/alfresco/WEB-INF/lib/onlyoffice-integration-repo.jar!/alfresco/extension/onlyoffice-context.xml]: Could not resolve parent bean definition 'baseContentTransformer'; nested exception is org.springframework.beans.factory.NoSuchBeanDefinitionException: No bean named 'baseContentTransformer' available

	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1788)

	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:609)

	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:531)

	at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:335)

	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:234)

	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:333)

	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:208)

	at org.springframework.beans.factory.support.DefaultListableBeanFactory.preInstantiateSingletons(DefaultListableBeanFactory.java:944)

	at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:923)

	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:588)

	at org.springframework.web.context.ContextLoader.configureAndRefreshWebApplicationContext(ContextLoader.java:401)

	at org.springframework.web.context.ContextLoader.initWebApplicationContext(ContextLoader.java:292)

	at org.springframework.web.context.ContextLoaderListener.contextInitialized(ContextLoaderListener.java:103)

	at org.alfresco.web.app.ContextLoaderListener.contextInitialized(ContextLoaderListener.java:70)

	at org.apache.catalina.core.StandardContext.listenerStart(StandardContext.java:4716)

	at org.apache.catalina.core.StandardContext.startInternal(StandardContext.java:5177)

	at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:183)

	at org.apache.catalina.core.ContainerBase.addChildInternal(ContainerBase.java:717)

	at org.apache.catalina.core.ContainerBase.access$000(ContainerBase.java:129)

	at org.apache.catalina.core.ContainerBase$PrivilegedAddChild.run(ContainerBase.java:150)

	at org.apache.catalina.core.ContainerBase$PrivilegedAddChild.run(ContainerBase.java:140)

	at java.base/java.security.AccessController.doPrivileged(Native Method)

	at org.apache.catalina.core.ContainerBase.addChild(ContainerBase.java:688)

	at org.apache.catalina.core.StandardHost.addChild(StandardHost.java:706)

	at org.apache.catalina.startup.HostConfig.deployDirectory(HostConfig.java:1133)

	at org.apache.catalina.startup.HostConfig$DeployDirectory.run(HostConfig.java:1866)

	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)

	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)

	at org.apache.tomcat.util.threads.InlineExecutorService.execute(InlineExecutorService.java:75)

	at java.base/java.util.concurrent.AbstractExecutorService.submit(AbstractExecutorService.java:118)

	at org.apache.catalina.startup.HostConfig.deployDirectories(HostConfig.java:1045)

	at org.apache.catalina.startup.HostConfig.deployApps(HostConfig.java:429)

	at org.apache.catalina.startup.HostConfig.start(HostConfig.java:1576)

	at org.apache.catalina.startup.HostConfig.lifecycleEvent(HostConfig.java:309)

	at org.apache.catalina.util.LifecycleBase.fireLifecycleEvent(LifecycleBase.java:123)

	at org.apache.catalina.util.LifecycleBase.setStateInternal(LifecycleBase.java:423)

	at org.apache.catalina.util.LifecycleBase.setState(LifecycleBase.java:366)

	at org.apache.catalina.core.ContainerBase.startInternal(ContainerBase.java:936)

	at org.apache.catalina.core.StandardHost.startInternal(StandardHost.java:843)

	at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:183)

	at org.apache.catalina.core.ContainerBase$StartChild.call(ContainerBase.java:1384)

	at org.apache.catalina.core.ContainerBase$StartChild.call(ContainerBase.java:1374)

	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)

	at org.apache.tomcat.util.threads.InlineExecutorService.execute(InlineExecutorService.java:75)

	at java.base/java.util.concurrent.AbstractExecutorService.submit(AbstractExecutorService.java:140)

	at org.apache.catalina.core.ContainerBase.startInternal(ContainerBase.java:909)

	at org.apache.catalina.core.StandardEngine.startInternal(StandardEngine.java:262)

	at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:183)

	at org.apache.catalina.core.StandardService.startInternal(StandardService.java:434)

	at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:183)

	at org.apache.catalina.core.StandardServer.startInternal(StandardServer.java:930)

	at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:183)

	at org.apache.catalina.startup.Catalina.start(Catalina.java:772)

	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)

	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)

	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)

	at java.base/java.lang.reflect.Method.invoke(Method.java:566)

	at org.apache.catalina.startup.Bootstrap.start(Bootstrap.java:342)

	at org.apache.catalina.startup.Bootstrap.main(Bootstrap.java:473)

Caused by: org.springframework.beans.factory.BeanDefinitionStoreException: Invalid bean definition with name 'transformer.onlyoffice' defined in URL [jar:file:/usr/local/tomcat/webapps/alfresco/WEB-INF/lib/onlyoffice-integration-repo.jar!/alfresco/extension/onlyoffice-context.xml]: Could not resolve parent bean definition 'baseContentTransformer'; nested exception is org.springframework.beans.factory.NoSuchBeanDefinitionException: No bean named 'baseContentTransformer' available

	at org.springframework.beans.factory.support.AbstractBeanFactory.getMergedBeanDefinition(AbstractBeanFactory.java:1417)

	at org.springframework.beans.factory.support.AbstractBeanFactory.getMergedBeanDefinition(AbstractBeanFactory.java:1358)

	at org.springframework.beans.factory.support.AbstractBeanFactory.getMergedLocalBeanDefinition(AbstractBeanFactory.java:1344)

	at org.springframework.beans.factory.support.DefaultListableBeanFactory.doGetBeanNamesForType(DefaultListableBeanFactory.java:565)

	at org.springframework.beans.factory.support.DefaultListableBeanFactory.getBeanNamesForType(DefaultListableBeanFactory.java:550)

	at org.springframework.beans.factory.support.DefaultListableBeanFactory.getBeanNamesForType(DefaultListableBeanFactory.java:527)

	at org.springframework.beans.factory.support.DefaultListableBeanFactory.getBeanNamesForType(DefaultListableBeanFactory.java:520)

	at org.springframework.beans.factory.support.DefaultListableBeanFactory.resolveNamedBean(DefaultListableBeanFactory.java:1219)

	at org.springframework.beans.factory.support.DefaultListableBeanFactory.resolveBean(DefaultListableBeanFactory.java:494)

	at org.springframework.beans.factory.support.DefaultListableBeanFactory.resolveBean(DefaultListableBeanFactory.java:500)

	at org.springframework.beans.factory.support.DefaultListableBeanFactory.getBean(DefaultListableBeanFactory.java:349)

	at org.springframework.beans.factory.support.DefaultListableBeanFactory.getBean(DefaultListableBeanFactory.java:342)

	at org.springframework.context.support.AbstractApplicationContext.getBean(AbstractApplicationContext.java:1177)

	at org.alfresco.repo.admin.patch.impl.AdminUserPatch.afterPropertiesSet(AdminUserPatch.java:117)

	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.lambda$invokeInitMethods$5(AbstractAutowireCapableBeanFactory.java:1838)

	at java.base/java.security.AccessController.doPrivileged(Native Method)

	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.invokeInitMethods(AbstractAutowireCapableBeanFactory.java:1837)

	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1784)


	... 58 more

Caused by: org.springframework.beans.factory.NoSuchBeanDefinitionException: No bean named 'baseContentTransformer' available

	at org.springframework.beans.factory.support.DefaultListableBeanFactory.getBeanDefinition(DefaultListableBeanFactory.java:863)

	at org.springframework.beans.factory.support.AbstractBeanFactory.getMergedLocalBeanDefinition(AbstractBeanFactory.java:1344)

	at org.springframework.beans.factory.support.AbstractBeanFactory.getMergedBeanDefinition(AbstractBeanFactory.java:1132)

	at org.springframework.beans.factory.support.AbstractBeanFactory.getMergedBeanDefinition(AbstractBeanFactory.java:1401)


	... 75 more

26-Apr-2021 11:39:06.716 SEVERE [main] org.apache.catalina.core.StandardContext.startInternal One or more listeners failed to start. Full details will be found in the appropriate container log file

26-Apr-2021 11:39:06.721 SEVERE [main] org.apache.catalina.core.StandardContext.startInternal Context [/alfresco] startup failed due to previous errors`

**Comment by sjeandroz** [comment]
Hello @renatofritola 

I have exactly the same error message when try to update Alfresco from 6 to 7

Have you managed to resolve it ?

Thanks!

Best

Sylvain
